name: Sync iptv4.m3u to mytv

on:
  schedule:
    - cron: '0 8 * * *'   # 每天 00:00 自动运行
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout A repo (iptv)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone B repo (mytv)
        run: |
          git clone https://github.com/lyiehf/mytv.git target-repo
          cd target-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Copy iptv4.m3u to B repo
        run: |
          cp iptv/tv/iptv4.m3u target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git add .
          git commit -m "Auto sync iptv4.m3u from iptv repo" || echo "No changes to commit"
          git push https://$PAT@github.com/lyiehf/mytv.git
        env:
          PAT: ${{ secrets.PAT }}